/*
 * Automatically generated by cbindgen.
 * Do not edit this file manually.
 *
 * SPDX-License-Identifier: MIT
 */


#ifndef LIBRTMP2_H
#define LIBRTMP2_H

#pragma once

/* Generated with cbindgen:0.29.4 */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define MAX_OBJECT_KEYS 256

/**
 * Maximum buffer size: 64 MB
 */
#define BUFFER_MAX_SIZE ((64 * 1024) * 1024)

/**
 * Initial buffer capacity
 */
#define BUFFER_INITIAL_SIZE 4096

/**
 * Capacity retained after [`Buffer::reset`] so short-lived large messages
 * cannot leave multi-megabyte `Vec` allocations pinned for the connection.
 */
#define BUFFER_RESET_CAPACITY BUFFER_INITIAL_SIZE

/**
 * Default chunk size per RTMP spec
 */
#define DEFAULT_CHUNK_SIZE 128

/**
 * Upper bound on distinct chunk streams
 */
#define MAX_CHUNK_STREAMS 4096

/**
 * Max reassembly bytes per connection
 */
#define MAX_REASSEMBLY_BYTES_PER_CONN ((32 * 1024) * 1024)

/**
 * Default cap on a single RTMP message body (24-bit length field allows 16 MiB).
 */
#define DEFAULT_MAX_MSG_LENGTH ((4 * 1024) * 1024)

/**
 * Default cap on concurrently active chunk-stream ids per connection.
 */
#define DEFAULT_MAX_ACTIVE_CSIDS 256

/**
 * Maximum frame payload accepted from FFI callers.
 */
#define MAX_CLIENT_FRAME_BYTES (size_t)DEFAULT_MAX_MSG_LENGTH

#define ERTMP_AUDIO_PACKET_TYPE_MULTITRACK 5

#define ERTMP_VIDEO_PACKET_TYPE_MULTITRACK 6

/**
 * Cap sub-tracks unpacked from a single multitrack container (mirrors
 * `message::message::MAX_AGGREGATE_SUBTAGS` and `session::conn::MAX_AGGREGATE_SUBTAGS`).
 */
#define MAX_MULTITRACK_SUBTRACKS 4096

#define CTRL_SET_CHUNK_SIZE 1

#define CTRL_ABORT_MESSAGE 2

#define CTRL_ACKNOWLEDGEMENT 3

#define CTRL_USER_CONTROL 4

#define CTRL_WINDOW_ACK_SIZE 5

#define CTRL_SET_PEER_BANDWIDTH 6

#define UCTRL_STREAM_BEGIN 0

#define UCTRL_STREAM_EOF 1

#define UCTRL_STREAM_DRY 2

#define UCTRL_SET_BUFFER_LENGTH 3

#define UCTRL_STREAM_IS_RECORDED 4

#define UCTRL_PING_REQUEST 6

#define UCTRL_PING_RESPONSE 7

/**
 * Upper bound for peer-requested inbound chunk sizes (memory churn protection).
 */
#define MAX_INBOUND_CHUNK_SIZE 65536

/**
 * Reject peer WindowAckSize values below this to prevent ACK-per-byte amplification.
 */
#define MIN_WINDOW_ACK_SIZE 1024

#define RTMP_MSG_SET_CHUNK_SIZE 1

#define RTMP_MSG_ABORT_MESSAGE 2

#define RTMP_MSG_ACKNOWLEDGEMENT 3

#define RTMP_MSG_USER_CONTROL 4

#define RTMP_MSG_WINDOW_ACK_SIZE 5

#define RTMP_MSG_SET_PEER_BANDWIDTH 6

#define RTMP_MSG_AUDIO 8

#define RTMP_MSG_VIDEO 9

#define RTMP_MSG_AMF3_DATA 15

#define RTMP_MSG_AMF3_SHARED_OBJECT 16

#define RTMP_MSG_AMF3_COMMAND 17

#define RTMP_MSG_AMF0_DATA 18

#define RTMP_MSG_AMF0_COMMAND 20

#define RTMP_MSG_AGGREGATE 22

/**
 * Default max simultaneous connections accepted per remote address when
 * `ServerConfig::max_connections_per_addr` is `0` (unset). Prevents one peer
 * from monopolizing the global connection table on plaintext listeners.
 * Deployments where many clients share one source IP (NAT/load balancer/proxy)
 * can raise this via `ServerConfig::max_connections_per_addr`.
 */
#define DEFAULT_MAX_CONNECTIONS_PER_ADDR 4

/**
 * Default max incomplete TLS handshakes retained per remote address, used
 * when `ServerConfig::max_pending_tls_per_addr` is `0` (unset). Prevents one
 * peer from monopolizing the global pending queue. Deployments where many
 * clients share one source IP (NAT/load balancer/proxy) can raise this via
 * `ServerConfig::max_pending_tls_per_addr`.
 */
#define DEFAULT_MAX_PENDING_TLS_PER_ADDR DEFAULT_MAX_CONNECTIONS_PER_ADDR

/**
 * Default cap on relay sends issued while fanning publisher media out to
 * players in one `process_connections` pass. Integrators can tune the active
 * value through [`Server::max_relay_sends_per_poll`].
 */
#define DEFAULT_MAX_RELAY_SENDS_PER_POLL 4096

#define MAX_STREAMS_PER_CONN 16

#define MAX_PENDING_RELAY_FRAMES 1024

#define MAX_PENDING_RELAY_BYTES ((8 * 1024) * 1024)

/**
 * Enhanced RTMP v1 VideoPacketType
 */
#define ERTMP_PACKET_TYPE_SEQUENCE_START 0

#define ERTMP_PACKET_TYPE_CODED_FRAMES 1

#define ERTMP_PACKET_TYPE_SEQUENCE_END 2

#define ERTMP_PACKET_TYPE_CODED_FRAMES_X 3

#define ERTMP_PACKET_TYPE_METADATA 4

#define ERTMP_PACKET_TYPE_MPEG2TS_SEQUENCE_START 5

/**
 * Enhanced RTMP v1/v2 AudioPacketType
 */
#define ERTMP_AUDIO_PACKET_TYPE_SEQUENCE_START 0

#define ERTMP_AUDIO_PACKET_TYPE_CODED_FRAMES 1

#define ERTMP_AUDIO_PACKET_TYPE_SEQUENCE_END 2

#define ERTMP_AUDIO_PACKET_TYPE_METADATA 3

#define ERTMP_AUDIO_PACKET_TYPE_MULTICHANNEL 4

/**
 * E-RTMP v2 `CapsExMask` bits carried in the connect `capsEx` AMF number.
 */
#define CAPS_EX_MASK_RECONNECT 1

#define CAPS_EX_MASK_MULTITRACK 2

#define CAPS_EX_MASK_MODEX 4

#define CAPS_EX_MASK_TIMESTAMP_NANO 8

#define CAPS_EX_MASK_SERVER_DEFAULT ((CAPS_EX_MASK_MULTITRACK | CAPS_EX_MASK_MODEX) | CAPS_EX_MASK_TIMESTAMP_NANO)

/**
 * Enhanced RTMP v1 AudioSampleRate (legacy)
 */
#define ERTMP_AUDIO_RATE_5500 0

#define ERTMP_AUDIO_RATE_11025 1

#define ERTMP_AUDIO_RATE_22050 2

#define ERTMP_AUDIO_RATE_44100 3

/**
 * Enhanced RTMP v1 AudioSampleSize (legacy)
 */
#define ERTMP_AUDIO_SAMPLE_8BIT 0

#define ERTMP_AUDIO_SAMPLE_16BIT 1

/**
 * Maximum number of FourCC entries in a list.
 */
#define MAX_FOURCCS 16

/**
 * E-RTMP v2 per-codec capability flags.
 */
#define FOUR_CC_INFO_CAN_DECODE 1

#define FOUR_CC_INFO_CAN_ENCODE 2

#define FOUR_CC_INFO_CAN_FORWARD 4

#define FOUR_CC_INFO_ALL ((FOUR_CC_INFO_CAN_DECODE | FOUR_CC_INFO_CAN_ENCODE) | FOUR_CC_INFO_CAN_FORWARD)

/**
 * Frame type classification.
 */
typedef enum FrameType {
  Audio = 0,
  Video = 1,
  Script = 2,
  Metadata = 3,
} FrameType;

/**
 * Audio codec identifiers.
 */
typedef enum AudioCodec {
  Pcm = 0,
  Adpcm = 1,
  Mp3 = 2,
  PcmLe = 3,
  Nelly16k = 4,
  Nelly8k = 5,
  Nelly = 6,
  G711A = 7,
  G711U = 8,
  Aac = 10,
  Speex = 11,
  Opus = 14,
} AudioCodec;

/**
 * Video codec identifiers (legacy).
 */
typedef enum VideoCodec {
  Jpeg = 1,
  Sorenson = 2,
  Screen = 3,
  Vp6 = 4,
  Vp6a = 5,
  Screen2 = 6,
  H264 = 7,
  H265 = 12,
  Av1 = 13,
  Vp9 = 14,
} VideoCodec;

/**
 * Opaque server handle
 */
typedef struct lrtmp2_server_t {
  uint8_t _private[0];
} lrtmp2_server_t;

/**
 * Server configuration struct.
 */
typedef struct lrtmp2_server_config_t {
  int max_connections;
  int chunk_size;
  /**
   * TLS / RTMPS fields
   */
  int tls_enabled;
  /**
   * Server: PEM certificate chain file
   */
  const uint8_t *tls_cert_file;
  /**
   * Server: PEM private key file
   */
  const uint8_t *tls_key_file;
  /**
   * Client: CA bundle for verification (or NULL)
   */
  const uint8_t *tls_ca_file;
  /**
   * Client: skip certificate verification
   */
  int tls_insecure;
  /**
   * Max incomplete TLS handshakes retained per remote peer IP before the
   * oldest is evicted to admit a new one. `0` (or negative) uses the
   * built-in default (see `server::DEFAULT_MAX_PENDING_TLS_PER_ADDR`).
   * Appended field: see `docs/abi-policy.md` (config struct fields may be
   * appended between minor releases).
   */
  int max_pending_tls_per_addr;
  /**
   * Max active (already-accepted) connections retained per remote peer
   * IP. `0` (or negative) uses the built-in default (see
   * `server::DEFAULT_MAX_CONNECTIONS_PER_ADDR`). Kept independent of
   * `max_pending_tls_per_addr` so tuning one does not change the other:
   * they defend different resources (the connection table vs. the
   * pending-handshake queue). Appended field: see `docs/abi-policy.md`.
   */
  int max_connections_per_addr;
} lrtmp2_server_config_t;

/**
 * Opaque client handle
 */
typedef struct lrtmp2_client_t {
  uint8_t _private[0];
} lrtmp2_client_t;

/**
 * FourCC code for Enhanced RTMP.
 */
typedef struct FourCc {
  /**
   * null-terminated, e.g. "hvc1"
   */
  uint8_t cc[5];
} FourCc;

/**
 * A parsed frame delivered via the `on_frame` callback.
 */
typedef struct lrtmp2_frame_t {
  enum FrameType frame_type;
  uint32_t timestamp;
  uint32_t composition_time;
  uint32_t size;
  const uint8_t *data;
  /**
   * Audio-specific
   */
  enum AudioCodec audio_codec;
  uint32_t audio_sample_rate;
  uint8_t audio_channels;
  uint8_t audio_bit_depth;
  /**
   * Enhanced: FourCC from ExAudioTagHeader
   */
  struct FourCc audio_fourcc;
  /**
   * Video-specific
   */
  enum VideoCodec video_codec;
  struct FourCc video_fourcc;
  /**
   * 1=keyframe, 2=inter, etc.
   */
  uint8_t video_frame_type;
  /**
   * Script/metadata flag
   */
  uint8_t is_metadata;
  /**
   * E-RTMP multitrack id (0 = default track; 255 = not set / single-track).
   */
  uint8_t track_id;
} lrtmp2_frame_t;

/**
 * Opaque connection handle
 */
typedef struct lrtmp2_conn_t {
  uint8_t _private[0];
} lrtmp2_conn_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a server (FFI-compatible).
 */
struct lrtmp2_server_t *lrtmp2_server_create(const struct lrtmp2_server_config_t *config);

/**
 * Destroy a server (FFI-compatible).
 */
void lrtmp2_server_destroy(struct lrtmp2_server_t *server);

/**
 * Start listening (FFI-compatible).
 */
int32_t lrtmp2_server_listen(struct lrtmp2_server_t *server, const char *bind_addr);

/**
 * Poll for events (FFI-compatible).
 */
int32_t lrtmp2_server_poll(struct lrtmp2_server_t *server, int32_t timeout_ms);

/**
 * Stop the server (FFI-compatible).
 */
void lrtmp2_server_stop(struct lrtmp2_server_t *server);

/**
 * Create a client (FFI-compatible). `config` may be NULL to use defaults
 * (verify `rtmps://` peers against the system trust store). When non-NULL,
 * `config.tls_ca_file` (a CA bundle to trust instead of the system store)
 * and `config.tls_insecure` (skip verification entirely, for testing only)
 * control `rtmps://` verification for this client. Returns NULL if
 * `tls_ca_file` is non-NULL but not valid UTF-8, rather than silently
 * falling back to default verification.
 */
struct lrtmp2_client_t *lrtmp2_client_create(const struct lrtmp2_server_config_t *config);

/**
 * Destroy a client (FFI-compatible).
 */
void lrtmp2_client_destroy(struct lrtmp2_client_t *c);

/**
 * Connect (FFI-compatible).
 */
int32_t lrtmp2_client_connect(struct lrtmp2_client_t *c, const char *url);

/**
 * Publish (FFI-compatible).
 */
int32_t lrtmp2_client_publish(struct lrtmp2_client_t *c);

/**
 * Play (FFI-compatible).
 */
int32_t lrtmp2_client_play(struct lrtmp2_client_t *c);

/**
 * Send a frame (FFI-compatible).
 */
int32_t lrtmp2_client_send_frame(struct lrtmp2_client_t *c, const struct lrtmp2_frame_t *frame);

/**
 * Poll client (FFI-compatible).
 */
int32_t lrtmp2_client_poll(struct lrtmp2_client_t *c, int32_t timeout_ms);

/**
 * Get connection fd (FFI-compatible).
 */
int32_t lrtmp2_conn_get_fd(const struct lrtmp2_conn_t *_conn);

/**
 * Check TLS support (FFI-compatible).
 */
int32_t lrtmp2_tls_supported(void);

/**
 * Get version string (FFI-compatible).
 */
const char *lrtmp2_version_string(void);

/**
 * Get major version (FFI-compatible).
 */
int32_t lrtmp2_version_major(void);

/**
 * Get minor version (FFI-compatible).
 */
int32_t lrtmp2_version_minor(void);

/**
 * Get patch version (FFI-compatible).
 */
int32_t lrtmp2_version_patch(void);

/**
 * Get error string (FFI-compatible).
 *
 * Takes a raw `i32` rather than `ErrorCode` so that an out-of-range value
 * from a caller (e.g. a weakly-typed binding forwarding an unrelated int)
 * cannot construct an invalid enum discriminant, which would be undefined
 * behavior.
 */
const char *lrtmp2_error_string(int32_t code);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LIBRTMP2_H */
