name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  unit-tests-make:
    name: unit tests (make, ${{ matrix.cc }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]
    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y meson ninja-build

    - name: Compile (release, sanity)
      run: make release
      env:
        CC: ${{ matrix.cc }}

    - name: Run unit tests
      run: make test
      env:
        CC: ${{ matrix.cc }}

    - name: Run unit tests (ASan)
      run: make clean && make DEBUG=1 ASAN=1 test
      env:
        CC: ${{ matrix.cc }}

    - name: Run unit tests (UBSan)
      run: make clean && make DEBUG=1 UBSAN=1 test
      env:
        CC: ${{ matrix.cc }}

  unit-tests-meson:
    name: unit tests (meson)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y meson ninja-build

    - name: Meson setup
      run: meson setup builddir

    - name: Meson compile
      run: meson compile -C builddir

    - name: Run unit tests
      run: meson test -C builddir
